### ISSUE TITLE
Type error in README

### ISSUE THREAD

**Issue by MarioAPGS** [matthijskooijman/gnome-shell-more-keyboard-shortcuts#1]
there is an error with the url of the repo in the instalation guide:
git://github.com/matthijskooijman/gnome-shell-more-keyboard-shortcuts

should be with https

https://github.com/matthijskooijman/gnome-shell-more-keyboard-shortcuts

**Comment by matthijskooijman** [comment]
Thanks for reporting! I've fixed it right away.

Nice to see some activity in this repo. Are you using the extension?
